version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"

    assignees:
      - mkody

  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase

    schedule:
      interval: "daily"

    assignees:
      - mkody

    groups:
      simple:
        update-types:
          - "major"
          - "minor"
          - "patch"

        patterns:
          - "simple-icons"
