version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"

    assignees:
      - mkody

  - package-ecosystem: npm
    directory: "/buildTools"
    versioning-strategy: increase

    schedule:
      interval: "daily"

    assignees:
      - mkody

    allow:
      - dependency-name: "simple-icons"
