name: Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Build package
        run: |
          pnpm install
          pnpm build

      - name: Build example
        run: |
          cd example/
          pnpm install
          pnpm build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'example/dist/'

  deploy:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v3
