name: Publish Package to npmjs

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install buildTools dependencies
        run: |
          cd buildTools
          deno install --entrypoint ./src/main.ts

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --provenance --access public --no-git-checks
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
